import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container:   { flex: 1, backgroundColor: '#161618' },
  splitLayout: { flex: 1, flexDirection: 'row' },

  // 모드 선택 화면
  modeContainer:   { flex: 1, backgroundColor: '#000', alignItems: 'center', justifyContent: 'center' },
  modeTitleBlock:  { alignItems: 'center', marginBottom: 56 },
  modeLogo:        { fontSize: 40, fontWeight: '800', color: '#fff', letterSpacing: -1.5 },
  modeTagline:     { fontSize: 15, color: '#636366', marginTop: 6, letterSpacing: -0.2 },
  modeCardRow:     { flexDirection: 'row', gap: 12 },
  modeCard:        { width: 148, backgroundColor: '#1C1C1E', borderRadius: 18, borderWidth: 1, borderColor: '#38383A', padding: 24, alignItems: 'center', gap: 10 },
  modeCardEmoji:   { fontSize: 34 },
  modeCardLabel:   { fontSize: 17, fontWeight: '600', color: '#fff', letterSpacing: -0.3 },
  modeCardDesc:    { fontSize: 12, color: '#636366', textAlign: 'center', lineHeight: 17 },

  // 탑바
  tableSection:    { flex: 1 },
  tableTopBar:     { flexDirection: 'column', paddingHorizontal: 16, paddingTop: 16, paddingBottom: 12, gap: 10, borderBottomWidth: StyleSheet.hairlineWidth },
  headerTitleRow:  { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  headerLeft:      { flexDirection: 'row', alignItems: 'center', gap: 8 },
  timeViewTabs:    { flexDirection: 'row', gap: 2, borderRadius: 10, padding: 3, borderWidth: 1 },
  timeViewTab:     { paddingHorizontal: 13, paddingVertical: 5, borderRadius: 7 },
  timeViewTabActive: { shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 4, shadowOffset: { width: 0, height: 1 } },
  timeViewTabText: { fontSize: 13, fontWeight: '500', letterSpacing: -0.1 },
  timeViewTabTextActive: { fontWeight: '600' },
  headerTitle:     { fontSize: 22, fontWeight: '700', color: '#fff', letterSpacing: -0.8 },
  headerUser:      { fontSize: 13, color: '#636366', fontWeight: '400' },
  modePill:        { borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4, borderWidth: 1 },
  modePillText:    { fontSize: 12, fontWeight: '500' },
  headerRight:     { flexDirection: 'row', alignItems: 'center', gap: 6, justifyContent: 'flex-end' },
  iconBtn:         { padding: 6 },
  clearAllBtn:     { paddingHorizontal: 10, paddingVertical: 4, backgroundColor: 'rgba(0,122,255,0.13)', borderRadius: 20 },
  clearAllText:    { color: '#007AFF', fontSize: 12, fontWeight: '500' },
  addBtn:          { width: 30, height: 30, borderRadius: 15, backgroundColor: '#007AFF', alignItems: 'center', justifyContent: 'center' },

  // 검색바
  searchBox:        { flexGrow: 1, minWidth: 120, flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1 },
  searchInput:      { flex: 1, fontSize: 13, padding: 0 },

  // 필터 칩 바
  filterBar:        { borderBottomWidth: 1 },
  filterBarContent: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 12, paddingVertical: 8 },
  filterBarCount:   { marginLeft: 4, justifyContent: 'center' },
  filterBarCountText: { fontSize: 11 },

  // 필터 칩 (ColFilter)
  colHeader:        { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 20, paddingHorizontal: 12, paddingVertical: 6, borderWidth: 1 },
  colHeaderFiltered:{ },
  colHeaderText:    { fontSize: 12, fontWeight: '500' },
  colHeaderIcons:   { flexDirection: 'row', alignItems: 'center', gap: 2 },

  // 컬럼 헤더 행
  colHeaderRow:     { flexDirection: 'row', borderBottomWidth: StyleSheet.hairlineWidth, paddingVertical: 7, paddingHorizontal: 6 },
  colHeaderCell:    { flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 6 },
  colHeaderCellFlex:{ flex: 1 },
  colHeaderLabel:   { fontSize: 11, fontWeight: '600', letterSpacing: 0.3, textTransform: 'uppercase' } as any,
  rowCount:         { fontSize: 11, paddingHorizontal: 14, paddingVertical: 5 },

  // 캘린더 공통 (월간/주간)
  calNavRow:        { flexDirection: 'row', alignItems: 'center', paddingVertical: 10, paddingHorizontal: 12 },
  calNavBtn:        { padding: 6 },
  calNavTitle:      { color: '#fff', fontSize: 14, fontWeight: '600', flex: 1, textAlign: 'center', letterSpacing: -0.3 },
  calNavActions:    { flexDirection: 'row', alignItems: 'center', gap: 8 },
  calCellWeekend:   { opacity: 0.5 },
  weekCell:         { minHeight: 160 },
  calWeekHeader:    { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#2C2C2E' },
  calWeekCell:      { flex: 1, padding: 5, borderRightWidth: 1, borderRightColor: '#2C2C2E', alignItems: 'center' },
  calWeekLabel:     { textAlign: 'center', color: '#636366', fontSize: 11, fontWeight: '600', letterSpacing: 0.2 },
  calWeekLabelWeekend: { color: '#48484A' },
  calRow:           { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#2C2C2E' },
  calCell:          { flex: 1, minHeight: 80, padding: 5, borderRightWidth: 1, borderRightColor: '#2C2C2E' },
  calCellToday:     { backgroundColor: 'rgba(0,122,255,0.06)' },
  calDayNum:        { fontSize: 11, color: '#636366', marginBottom: 3 },
  calDayNumToday:   { color: '#007AFF', fontWeight: '700' },
  calDayWeekend:    { color: '#48484A' },
  calTaskChip:         { borderRadius: 4, paddingHorizontal: 5, paddingVertical: 2, marginBottom: 2 },
  calTaskText:         { fontSize: 10, fontWeight: '500' },
  calMilestoneBanner:  { borderLeftWidth: 2, borderLeftColor: '#5AC8FA', backgroundColor: 'rgba(90,200,250,0.12)', paddingHorizontal: 4, paddingVertical: 2, marginBottom: 2, borderRadius: 3 },
  calMilestoneText:    { fontSize: 10, color: '#5AC8FA', fontWeight: '600' },
  calMore:          { fontSize: 10, color: '#636366', marginTop: 1 },

  // 리스트 행
  listRow:          { flexDirection: 'row', alignItems: 'stretch', paddingVertical: 11, paddingRight: 14, borderBottomWidth: 0.5 },
  listRowSchedule:  { borderLeftWidth: 2, borderLeftColor: '#5AC8FA', backgroundColor: 'rgba(90,200,250,0.05)' },
  listRowContent:   { flex: 1, paddingLeft: 12 },
  listRowTop:       { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 0 },
  listRowTitle:     { flex: 1, fontSize: 14, fontWeight: '400', letterSpacing: -0.2 },
  listRowMeta:      { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginTop: 5 },
  typeIndicator:    { width: 3, borderRadius: 1.5, alignSelf: 'stretch', marginTop: 2, marginBottom: 2, marginLeft: 4 },
  tableRow:         { flexDirection: 'row', alignItems: 'center', paddingVertical: 11, paddingHorizontal: 8, borderBottomWidth: StyleSheet.hairlineWidth },
  tableRowSelected: { backgroundColor: 'rgba(0,122,255,0.10)' },
  tableRowSchedule: { borderLeftWidth: 2, borderLeftColor: '#5AC8FA' },
  tableCell:        { paddingHorizontal: 6, justifyContent: 'center', alignItems: 'flex-start' },
  tableCellFlex:    { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 6, flexWrap: 'wrap' },
  cellTitle:        { flex: 1, fontSize: 14, letterSpacing: -0.2 },
  cellEmpty:        { fontSize: 12 },

  // 태그
  tagProduct:       { borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  tagProductText:   { fontSize: 10, fontWeight: '600' },
  tagMilestone:     { borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  tagMilestoneText: { fontSize: 10, fontWeight: '600' },
  tagIssueInline:   { flexDirection: 'row', alignItems: 'center', gap: 3, backgroundColor: 'rgba(0,122,255,0.12)', borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 },
  tagIssueText:     { color: '#007AFF', fontSize: 10, fontWeight: '500' },
  statusPill:       { borderRadius: 5, paddingHorizontal: 8, paddingVertical: 3, alignItems: 'center', justifyContent: 'center', borderWidth: 1 },
  statusPillText:   { fontSize: 11, fontWeight: '600', letterSpacing: -0.1 },

  // 드롭다운
  dropOverlay:      { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)' },
  dropSheet:        { position: 'absolute', top: 100, left: 20, right: 20, backgroundColor: '#2C2C2E', borderRadius: 14, padding: 16, maxWidth: 260, shadowColor: '#000', shadowOpacity: 0.4, shadowRadius: 20, shadowOffset: { width: 0, height: 8 } },
  dropTitle:        { color: '#8E8E93', fontSize: 11, fontWeight: '600', letterSpacing: 0.4, marginBottom: 10 },
  dropSortRow:      { flexDirection: 'row', gap: 8, marginBottom: 8 },
  dropSortBtn:      { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 5, padding: 8, backgroundColor: '#3A3A3C', borderRadius: 9 },
  dropSortActive:   { borderWidth: 1, borderColor: 'rgba(0,122,255,0.27)' },
  dropSortText:     { color: '#8E8E93', fontSize: 12 },
  dropDivider:      { height: 1, backgroundColor: '#3A3A3C', marginVertical: 8 },
  dropOption:       { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 10, paddingHorizontal: 4, borderBottomWidth: 1, borderBottomColor: '#3A3A3C' },
  dropOptionActive: {},
  dropOptionText:   { color: 'rgba(235,235,245,0.85)', fontSize: 13 },

  empty:        { alignItems: 'center', marginTop: 80, paddingHorizontal: 32 },
  emptyText:    { color: '#636366', fontSize: 16, fontWeight: '500', letterSpacing: -0.3 },
  emptySubText: { color: '#48484A', fontSize: 13, marginTop: 8, textAlign: 'center', lineHeight: 19 },

  // 상세 패널
  detailModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'center', alignItems: 'center' },
  detailPanel:        { borderRadius: 18, borderWidth: 1, maxHeight: '95%', width: '98%', maxWidth: 1080, shadowColor: '#000', shadowOpacity: 0.5, shadowRadius: 32, shadowOffset: { width: 0, height: 12 }, overflow: 'hidden' },
  detailPanelHeader:  { flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', paddingHorizontal: 14, paddingVertical: 10, borderBottomWidth: 1 },
  detailCompactHeader:{ flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14, paddingVertical: 8, borderBottomWidth: StyleSheet.hairlineWidth, gap: 6 },
  detailTitleInput:   { flex: 1, fontSize: 15, fontWeight: '600', letterSpacing: -0.3, padding: 0 },
  detailIconBtn:      { padding: 6 },
  detailPanelLabel:   { flex: 1, fontSize: 11, fontWeight: '600', marginRight: 8 },
  detailPanelActions: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  detailDeleteBtn:    { padding: 4 },
  detailPanelScroll:  { flex: 1, padding: 10 },
  twoColRow:          { flexDirection: 'row', gap: 0, marginTop: 2 },
  twoColPane:         { flex: 1, paddingHorizontal: 6 },
  twoColDivider:      { width: 1, marginHorizontal: 6 },
  twoColDividerH:     { height: 1, marginVertical: 12 },
  panelTitleInput:    { fontSize: 15, fontWeight: '600', borderRadius: 10, padding: 11, marginBottom: 8, minHeight: 42, borderWidth: 1, letterSpacing: -0.3 },
  panelNoteInput:     { fontSize: 13, borderRadius: 10, padding: 8, paddingHorizontal: 10, marginBottom: 4, height: 34, borderWidth: 1, letterSpacing: -0.1 },
  panelSectionLabel:  { fontSize: 10, fontWeight: '700', letterSpacing: 0.5, marginTop: 8, marginBottom: 3 },
  panelSectionRow:    { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 14, marginBottom: 6 },

  // 날짜
  dateBlock:        { borderRadius: 10, borderWidth: 1, overflow: 'hidden', marginBottom: 4 },
  dateRow:          { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingVertical: 7, borderBottomWidth: 0 },
  dateLabel:        { width: 34, fontSize: 11, fontWeight: '600' },
  dateValue:        { flex: 1, fontSize: 11 },

  // 미니 캘린더
  calBackdrop:      { flex: 1, backgroundColor: 'rgba(0,0,0,0.4)' },
  calCard:          { width: 218, backgroundColor: '#2C2C2E', borderRadius: 14, borderWidth: 1, borderColor: '#38383A', padding: 14, shadowColor: '#000', shadowOpacity: 0.4, shadowRadius: 16, shadowOffset: { width: 0, height: 6 } } as any,
  calHeader:        { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 },
  calNav:           { color: '#8E8E93', fontSize: 18, lineHeight: 20 },
  calTitle:         { color: '#fff', fontSize: 13, fontWeight: '600', letterSpacing: -0.2 },
  calWeekRow:       { flexDirection: 'row', marginBottom: 4 },
  calGrid:          { flexDirection: 'row', flexWrap: 'wrap' },
  calDayInner:      { width: 22, height: 22, borderRadius: 11, justifyContent: 'center', alignItems: 'center' },
  calDaySel:        { backgroundColor: '#007AFF' },
  calDayToday:      { borderWidth: 1, borderColor: 'rgba(0,122,255,0.33)' },
  calDayText:        { color: '#8E8E93', fontSize: 11 },
  calDayTextWeekend: { color: '#48484A' },
  calDayTextSel:     { color: '#fff', fontWeight: '700' },
  calDayTextToday:   { color: '#007AFF', fontWeight: '600' },
  calClearBtn:      { marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: '#3A3A3C', alignItems: 'center' },
  calClearText:     { color: '#8E8E93', fontSize: 11 },

  // 공통 칩
  chipRow:       { flexDirection: 'row', flexWrap: 'wrap', gap: 5 },
  chip:          { borderRadius: 8, paddingHorizontal: 9, paddingVertical: 4, borderWidth: 1 },
  chipActive:    { backgroundColor: 'rgba(0,122,255,0.13)', borderColor: '#007AFF' },
  chipText:      { fontSize: 12, fontWeight: '500' },
  chipTextActive:{ color: '#007AFF', fontWeight: '600' },

  saveBtn:       { backgroundColor: '#007AFF', borderRadius: 10, padding: 10, alignItems: 'center', marginTop: 10, marginBottom: 2 },
  saveBtnText:   { color: '#fff', fontWeight: '700', fontSize: 14, letterSpacing: -0.2 },
  saveErrorText: { color: '#FF453A', fontSize: 11, textAlign: 'center', marginBottom: 16, marginTop: 6 },

  // 체크리스트 (레거시)
  issueBlock:        { marginBottom: 8, backgroundColor: '#1C1C1E', borderRadius: 10, borderWidth: 1, borderColor: '#38383A', overflow: 'hidden' },
  issueChecklist:    { flexDirection: 'row', flexWrap: 'wrap', gap: 6, paddingHorizontal: 8, paddingVertical: 7, borderTopWidth: 1, borderTopColor: '#38383A' },
  checkItem:         { flexDirection: 'row', alignItems: 'center', gap: 4 },
  checkItemText:     { color: '#48484A', fontSize: 11 },
  checkItemTextDone: { color: '#007AFF' },

  // 체크리스트 (DetailPanel)
  checklistBlock:    { borderRadius: 10, borderWidth: 1, marginBottom: 2, overflow: 'hidden' },
  checklistRow:      { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 10, paddingVertical: 5, borderBottomWidth: 1 },
  enableToggleWrap:  { marginRight: 8, padding: 3 },
  toggleTrack:       { width: 24, height: 14, borderRadius: 7, backgroundColor: '#3A3A3C', justifyContent: 'center', paddingHorizontal: 1 },
  toggleTrackOn:     { backgroundColor: '#007AFF' },
  toggleKnob:        { width: 10, height: 10, borderRadius: 5, backgroundColor: 'rgba(255,255,255,0.4)', alignSelf: 'flex-start' },
  toggleKnobOn:      { backgroundColor: '#fff', alignSelf: 'flex-end' },
  checklistLabel:    { flex: 1, color: '#8E8E93', fontSize: 12, letterSpacing: -0.1 },
  checklistLabelOff: { color: '#48484A' },
  checklistLabelDone:{ color: '#007AFF' },
  removeCustomBtn:   { paddingHorizontal: 4 },
  removeCustomText:  { color: '#48484A', fontSize: 14, lineHeight: 16 },
  checkbox:          { width: 15, height: 15, borderRadius: 4, borderWidth: 1.5, borderColor: '#48484A', alignItems: 'center', justifyContent: 'center' },
  checkboxChecked:   { backgroundColor: '#007AFF', borderColor: '#007AFF' },
  checkboxDisabled:  { borderColor: '#2C2C2E' },
  checkmark:         { color: '#fff', fontSize: 9, fontWeight: '700', lineHeight: 13 },
  addCustomRow:      { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 11, paddingVertical: 7 },
  addCustomInput:    { flex: 1, color: '#8E8E93', fontSize: 12, padding: 0, letterSpacing: -0.1 },
  addCustomBtn:      { padding: 2 },

  // 이슈
  addIssueBtn:       { flexDirection: 'row', alignItems: 'center', gap: 3, paddingVertical: 2, paddingHorizontal: 8, backgroundColor: 'rgba(0,122,255,0.13)', borderRadius: 7 },
  addIssueBtnText:   { color: '#007AFF', fontSize: 11, fontWeight: '600' },
  issueEmptyBtn:     { flexDirection: 'row', alignItems: 'center', gap: 5, padding: 9, backgroundColor: '#2C2C2E', borderRadius: 9, borderWidth: 1, borderColor: '#38383A', borderStyle: 'dashed' },
  issueEmptyText:    { color: '#636366', fontSize: 11 },
  issueInputRow:     { flexDirection: 'row', alignItems: 'center', gap: 4, padding: 6 },
  issueRepoBtn:      { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#2C2C2E', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 6 },
  issueRepoBtnText:  { flex: 1, color: '#8E8E93', fontSize: 11 },
  issueHash:         { color: '#636366', fontSize: 13, fontWeight: '700' },
  issueNumberInput:  { width: 48, backgroundColor: '#2C2C2E', borderRadius: 8, padding: 5, color: '#fff', fontSize: 12, textAlign: 'center' },
  issueLinkBtn:      { padding: 5, backgroundColor: 'rgba(0,122,255,0.12)', borderRadius: 6 },
  issueRemoveBtn:    { padding: 3 },

  // 레포 피커
  repoPickerOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)' },
  repoPickerSheet:   { position: 'absolute', bottom: 0, left: 0, right: 0, backgroundColor: '#1C1C1E', borderTopLeftRadius: 22, borderTopRightRadius: 22, padding: 24, maxHeight: '70%', borderTopWidth: 1, borderTopColor: '#38383A' },
  repoPickerTitle:   { fontSize: 17, fontWeight: '600', color: '#fff', marginBottom: 14, letterSpacing: -0.3 },
  repoSearchInput:   { backgroundColor: '#2C2C2E', borderRadius: 11, padding: 11, color: '#fff', fontSize: 14, marginBottom: 14, borderWidth: 1, borderColor: '#38383A' },
  repoGroupLabel:    { color: '#636366', fontSize: 11, fontWeight: '600', letterSpacing: 0.4, marginTop: 12, marginBottom: 6 },
  repoItem:          { paddingVertical: 13, borderBottomWidth: 1, borderBottomColor: '#2C2C2E' },
  repoItemText:      { color: 'rgba(235,235,245,0.85)', fontSize: 14 },
  repoEmptyText:     { color: '#636366', textAlign: 'center', marginTop: 24 },
  repoDropdown:      { backgroundColor: '#2C2C2E', borderRadius: 10, borderWidth: 1, borderColor: '#38383A', marginTop: 4 },
  repoDropdownItem:  { paddingHorizontal: 11, paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: '#38383A' },
  repoDropdownText:  { color: '#8E8E93', fontSize: 12 },

  // 추가 모달
  addModalOverlay:     { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', justifyContent: 'flex-end' },
  addModalSheet:       { backgroundColor: '#1C1C1E', borderTopLeftRadius: 22, borderTopRightRadius: 22, padding: 24, paddingBottom: 40, borderTopWidth: 1, borderTopColor: '#38383A' },
  addModalHeader:      { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  addModalTitle:       { color: '#8E8E93', fontSize: 12, fontWeight: '600', letterSpacing: 0.4 },
  addModalDueDate:     { color: '#007AFF', fontSize: 11, marginTop: 2 },
  addModalInput:       { backgroundColor: '#2C2C2E', borderRadius: 12, padding: 14, color: '#fff', fontSize: 15, minHeight: 88, textAlignVertical: 'top', marginBottom: 14, borderWidth: 1, borderColor: '#38383A', letterSpacing: -0.2 },
  addModalBtnRow:      { flexDirection: 'row', gap: 10 },
  addModalBtnShell:    { flex: 1, backgroundColor: '#2C2C2E', borderRadius: 12, paddingVertical: 14, alignItems: 'center', borderWidth: 1, borderColor: '#38383A' },
  addModalBtnShellText:{ color: '#8E8E93', fontSize: 13, fontWeight: '600' },
  addModalBtnDetail:   { flex: 2, backgroundColor: '#007AFF', borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  addModalBtnDetailText:{ color: '#fff', fontSize: 13, fontWeight: '700', letterSpacing: -0.2 },

  // 타입 태그
  typeTag:      { minWidth: 16, borderRadius: 8, borderWidth: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 7, paddingVertical: 2 },
  typeTagText:  { fontSize: 10, fontWeight: '600' },
  typeTagPlain: { fontSize: 11, fontWeight: '500', color: '#636366' },

  // 체크리스트 도트
  checkDots:        { flexDirection: 'row', gap: 3, marginRight: 6 },
  checkDot:         { width: 5, height: 5, borderRadius: 3, backgroundColor: '#2C2C2E', borderWidth: 1, borderColor: '#3A3A3C' },
  checkDotDone:     { backgroundColor: '#007AFF', borderColor: '#007AFF' },
  checkDotDisabled: { opacity: 0.2 },

  // AddModal 타입 선택
  addTypeRow:       { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginBottom: 10 },
  addTypeChip:      { paddingHorizontal: 11, paddingVertical: 6, borderRadius: 9, backgroundColor: '#2C2C2E', borderWidth: 1, borderColor: '#38383A' },
  addTypeChipText:  { color: '#8E8E93', fontSize: 12, fontWeight: '600' },

  // GitHub 이슈 배지
  issueBadge:     { flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 8, borderWidth: 1, paddingHorizontal: 8, paddingVertical: 4 },
  issueBadgeText: { fontSize: 11, fontWeight: '600', letterSpacing: -0.2 },

  // 이슈 자동 생성
  issueGenBlock:    { backgroundColor: '#2C2C2E', borderRadius: 12, borderWidth: 1, borderColor: '#38383A', padding: 14, marginTop: 12, marginBottom: 4 },
  issueGenTitle:    { color: '#636366', fontSize: 11, fontWeight: '700', letterSpacing: 0.4, marginBottom: 10 },
  issueGenBtn:      { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#007AFF', borderRadius: 10, padding: 11, justifyContent: 'center', marginTop: 4 },
  issueGenBtnText:  { color: '#fff', fontSize: 13, fontWeight: '700', letterSpacing: -0.2 },
  issueGenMsg:      { marginTop: 8, color: '#636366', fontSize: 11, textAlign: 'center' },
  issueGenMsgOk:    { color: '#30D158' },

  // 이슈 미리보기 모달
  previewOverlay:        { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  previewSheet:          { backgroundColor: '#1C1C1E', borderTopLeftRadius: 22, borderTopRightRadius: 22, padding: 22, paddingBottom: 40, maxHeight: '92%', display: 'flex' as any, flexDirection: 'column' as any, borderTopWidth: 1, borderTopColor: '#38383A' },
  previewHeader:         { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  previewHeading:        { color: '#8E8E93', fontSize: 12, fontWeight: '600', letterSpacing: 0.4 },
  previewTabRow:         { flexDirection: 'row', gap: 3, marginBottom: 14, backgroundColor: '#2C2C2E', borderRadius: 10, padding: 3 },
  previewTab:            { flex: 1, paddingVertical: 7, alignItems: 'center', borderRadius: 8 },
  previewTabActive:      { backgroundColor: '#3A3A3C' },
  previewTabText:        { color: '#636366', fontSize: 12, fontWeight: '600' },
  previewTabTextActive:  { color: '#fff' },
  previewLabel:          { color: '#636366', fontSize: 11, fontWeight: '600', letterSpacing: 0.3, marginBottom: 6 },
  previewTitleInput:     { backgroundColor: '#2C2C2E', borderRadius: 11, padding: 13, color: '#fff', fontSize: 14, fontWeight: '600', marginBottom: 14, borderWidth: 1, borderColor: '#38383A', letterSpacing: -0.3 },
  previewBodyWrap:       { flex: 1, marginBottom: 16 },
  previewBodyInput:      { backgroundColor: '#2C2C2E', borderRadius: 11, padding: 13, color: 'rgba(235,235,245,0.72)', fontSize: 12, lineHeight: 18, height: 240, borderWidth: 1, borderColor: '#38383A', marginBottom: 16 },
  previewBtnRow:         { flexDirection: 'row', gap: 10 },
  previewBtnEmpty:       { flex: 1, backgroundColor: '#2C2C2E', borderRadius: 12, paddingVertical: 14, alignItems: 'center', borderWidth: 1, borderColor: '#38383A' },
  previewBtnEmptyText:   { color: '#8E8E93', fontSize: 13, fontWeight: '600' },
  previewBtnPost:        { flex: 2, backgroundColor: '#007AFF', borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  previewBtnPostText:    { color: '#fff', fontSize: 13, fontWeight: '700', letterSpacing: -0.2 },

  // 이슈 편집 패널 (오버레이)
  issuePanelHeader:     { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, borderBottomWidth: StyleSheet.hairlineWidth, gap: 8 },
  issuePanelBack:       { padding: 2 },
  issuePanelTitle:      { flex: 1, fontSize: 14, fontWeight: '600', letterSpacing: -0.3 },
  issuePanelTitleInput: { fontSize: 13, fontWeight: '600', borderRadius: 8, marginHorizontal: 12, marginTop: 8, marginBottom: 4, padding: 8, paddingHorizontal: 10, borderWidth: 1, letterSpacing: -0.3 },
  issueSectionBlock:    { marginTop: 8 },
  issueSectionLabel:    { fontSize: 11, fontWeight: '600', letterSpacing: 0.3, marginBottom: 4 },
  issueSectionInput:    { fontSize: 13, borderRadius: 8, padding: 8, paddingHorizontal: 10, borderWidth: 1, letterSpacing: -0.1, lineHeight: 18 },
  issueLinkBtn:         { width: 34, height: 34, borderRadius: 8, borderWidth: 1, alignItems: 'center', justifyContent: 'center', flexShrink: 0 },

  // 설정 모달
  settingsOverlay:    { flex: 1, backgroundColor: 'rgba(0,0,0,0.6)', alignItems: 'center', justifyContent: 'center' },
  settingsSheet:      { backgroundColor: '#1C1C1E', borderRadius: 20, padding: 24, width: '88%', maxWidth: 400, borderWidth: 1, borderColor: '#38383A', shadowColor: '#000', shadowOpacity: 0.5, shadowRadius: 24, shadowOffset: { width: 0, height: 8 } },
  settingsHeader:     { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 22 },
  settingsTitle:      { fontSize: 17, fontWeight: '700', color: '#fff', letterSpacing: -0.5 },
  settingsRow:        { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 4 },
  settingsRowLabel:   { fontSize: 15, color: '#fff', fontWeight: '500', letterSpacing: -0.2 },
  settingsRowDesc:    { fontSize: 12, color: '#636366', marginTop: 2 },
  settingsDivider:    { height: 1, backgroundColor: '#38383A', marginVertical: 18 },
  settingsGroupLabel: { fontSize: 11, color: '#8E8E93', fontWeight: '700', letterSpacing: 0.5, marginBottom: 5 },
  settingsGroupDesc:  { fontSize: 11, color: '#636366', lineHeight: 16, marginBottom: 10 },
  settingsInput:      { backgroundColor: '#2C2C2E', borderRadius: 11, padding: 12, color: '#fff', fontSize: 14, marginBottom: 4, borderWidth: 1, borderColor: '#48484A' },
  settingsBtnRow:     { flexDirection: 'row', gap: 10, marginTop: 22 },
  settingsCancelBtn:  { flex: 1, padding: 14, borderRadius: 12, backgroundColor: '#2C2C2E', alignItems: 'center', borderWidth: 1, borderColor: '#38383A' },
  settingsCancelText: { color: '#8E8E93', fontWeight: '600', fontSize: 15 },
  settingsSaveBtn:    { flex: 1, padding: 14, borderRadius: 12, backgroundColor: '#007AFF', alignItems: 'center' },
  settingsSaveText:   { color: '#fff', fontWeight: '700', fontSize: 15 },
  bigToggleTrack:     { width: 50, height: 30, borderRadius: 15, backgroundColor: '#38383A', padding: 2, justifyContent: 'center' },
  bigToggleTrackOn:   { backgroundColor: '#30D158' },
  bigToggleKnob:      { width: 26, height: 26, borderRadius: 13, backgroundColor: '#fff', alignSelf: 'flex-start', shadowColor: '#000', shadowOpacity: 0.25, shadowRadius: 4, shadowOffset: { width: 0, height: 2 } },
  bigToggleKnobOn:    { alignSelf: 'flex-end' },
});

export const markdownStyles = {
  body:       { color: '#ccc', fontSize: 13, lineHeight: 20, backgroundColor: 'transparent' },
  heading1:   { color: '#fff', fontSize: 17, fontWeight: '700' as const, marginTop: 16, marginBottom: 6 },
  heading2:   { color: '#fff', fontSize: 15, fontWeight: '700' as const, marginTop: 14, marginBottom: 4 },
  heading3:   { color: '#aaa', fontSize: 13, fontWeight: '700' as const, marginTop: 10, marginBottom: 4 },
  strong:     { color: '#fff', fontWeight: '700' as const },
  blockquote: { backgroundColor: '#1E1E1E', borderLeftColor: '#333', borderLeftWidth: 3, paddingLeft: 10, marginVertical: 4 },
  code_inline:{ backgroundColor: '#252525', color: '#007AFF', fontSize: 12 },
  fence:      { backgroundColor: '#1A1A1A', color: '#bbb', fontSize: 12 },
  hr:         { backgroundColor: '#222', height: 1, marginVertical: 10 },
  bullet_list_icon: { color: '#555' },
};

export const AI_LABEL_COLORS: Record<string, { text: string; bg: string }> = {
  '필수': { text: '#FF453A', bg: 'rgba(255,69,58,0.15)' },
  '권장': { text: '#FF9500', bg: 'rgba(255,149,0,0.15)' },
  '참고': { text: '#8E8E93', bg: 'rgba(142,142,147,0.15)' },
};
